/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "midnight-ink": "#091426",
        "prussian-navy": "#1A2942",
        "ice-slate": "#E2E8F0",
        "hairline-border": "#E2E8F0",
        error: "#ba1a1a",
        "primary-fixed-dim": "#C9C4BC",
        "on-secondary": "#ffffff",
        "on-primary-container": "#E2E8F0",
        secondary: "#6A6258",
        "surface-container": "#F4F1ED",
        tertiary: "#091426",
        "on-tertiary-fixed-variant": "#091426",
        "surface-container-highest": "#EAE5DF",
        "on-surface-variant": "#6A6258",
        "tertiary-fixed-dim": "#C9C4BC",
        "tertiary-container": "#1A2942",
        "tertiary-fixed": "#E2E8F0",
        "inverse-primary": "#1A2942",
        background: "#FFFFFF",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#E2E8F0",
        "on-background": "#091426",
        "surface-container-low": "#FAF8F5",
        "surface-container-lowest": "#FFFFFF",
        "surface-tint": "#6A6258",
        "inverse-on-surface": "#FFFFFF",
        "secondary-fixed": "#EAE5DF",
        primary: "#091426",
        "surface-container-high": "#EAE5DF",
        "surface-dim": "#EAE5DF",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#FFFFFF",
        "on-error-container": "#93000a",
        "secondary-container": "#EAE5DF",
        "on-secondary-fixed": "#091426",
        "on-error": "#ffffff",
        "primary-fixed": "#E2E8F0",
        "surface-bright": "#FFFFFF",
        "on-primary-fixed-variant": "#1A2942",
        "outline-variant": "#E2E8F0",
        "primary-container": "#1A2942",
        "surface-variant": "#EAE5DF",
        "on-tertiary": "#ffffff",
        "on-surface": "#091426",
        outline: "#6A6258",
        "on-secondary-fixed-variant": "#4A443C",
        surface: "#FFFFFF",
        "on-secondary-container": "#4A443C",
        "on-tertiary-fixed": "#FFFFFF",
        "inverse-surface": "#1A2942",
        "secondary-fixed-dim": "#D9D4CC",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "panel-width-fixed": "320px",
        "panel-width": "72px",
        "margin-page": "32px",
        "grid-gap": "32px",
        unit: "4px",
        gutter: "16px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "mono-data": ["'JetBrains Mono'", "monospace"],
      },
      fontSize: {
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": [
          "11px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        "title-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "display-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "mono-data": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
      boxShadow: {
        soft: "0 4px 20px -2px rgba(9, 20, 38, 0.05)",
      },
    },
  },
  plugins: [],
};
