/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "primary-fixed-dim": "#bcc7de",
        "on-secondary": "#ffffff",
        "on-primary-container": "#8590a6",
        secondary: "#5c5f61",
        "surface-container": "#e5eeff",
        tertiary: "#001624",
        "on-tertiary-fixed-variant": "#004c6e",
        "surface-container-highest": "#d3e4fe",
        "on-surface-variant": "#45474c",
        "tertiary-fixed-dim": "#89ceff",
        "tertiary-container": "#002c42",
        "tertiary-fixed": "#c9e6ff",
        "inverse-primary": "#bcc7de",
        background: "#f8f9ff",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#0099d9",
        "on-background": "#0b1c30",
        "surface-container-low": "#eff4ff",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#545f73",
        "inverse-on-surface": "#eaf1ff",
        "secondary-fixed": "#e0e3e5",
        primary: "#091426",
        "surface-container-high": "#dce9ff",
        "surface-dim": "#cbdbf5",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#111c2d",
        "on-error-container": "#93000a",
        "secondary-container": "#e0e3e5",
        "on-secondary-fixed": "#191c1e",
        "on-error": "#ffffff",
        "primary-fixed": "#d8e3fb",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed-variant": "#3c475a",
        "outline-variant": "#c5c6cd",
        "primary-container": "#1e293b",
        "surface-variant": "#d3e4fe",
        "on-tertiary": "#ffffff",
        "on-surface": "#0b1c30",
        outline: "#75777d",
        "on-secondary-fixed-variant": "#444749",
        surface: "#f8f9ff",
        "on-secondary-container": "#626567",
        "on-tertiary-fixed": "#001e2f",
        "inverse-surface": "#213145",
        "secondary-fixed-dim": "#c4c7c9",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "panel-width-fixed": "320px",
        "margin-page": "24px",
        "grid-gap": "12px",
        unit: "4px",
        gutter: "16px",
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "mono-data": ["'JetBrains Mono'", "monospace"],
      },
      fontSize: {
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": [
          "11px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        "title-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "display-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "mono-data": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
